[package]
name = "rust-dathost-scrimbot"
version = "0.1.0"
authors = ["MartinWienc <32913968+MartinWienc@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokio = { version = "0.2.0", features = ["full"] }
reqwest = { version = "0.10", features = ["json", "blocking"] }
serenity = "0.9.0-rc.0"
rand = "0.7.3"
serde = "1.0"
serde_yaml = "0.8"
